import Header from "./components/Header"
import Footer from "./components/Footer"
import '@/app/style.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="page">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
